### ISSUE TITLE
CondResBlock

### ISSUE THREAD

**Issue by ZeWang95** [yilundu/improved_contrastive_divergence#7]
Hi Yilun,

Just a quick question. According to your implementation of CondResBlock, it seems there is actually no residual connection, as the x_orig = x is actually never used again in forward. May I ask whether you did this on purpose?

Thanks!

**Comment by yilundu** [comment]
Thanks for catching that! Sorry, in the process of refactoring my code this line must have been omitted. The residual connection is definitely helpful for performance.
