### ISSUE TITLE
Is Reservoir Sampling Important for the Performance?

### ISSUE THREAD

**Issue by GloryyrolG** [yilundu/improved_contrastive_divergence#8]
Hi Yilun @yilundu ,

Thanks for your excellent contribution. I noticed you used a different type of replay buffers, i.e., Reservoir instead of the original replay one.

https://github.com/yilundu/improved_contrastive_divergence/blob/master/train.py#L96

However, I did not find any details in your paper regarding this point. Correct me if I were wrong.

Thanks.

**Comment by yilundu** [comment]
Hi,

So the reservoir buffer is implemented in the codebase, but as long as the --reservoir flag is not activated, it is not used. It is not used in the default results in the paper.

**Comment by GloryyrolG** [comment]
Cool. Maybe you can consider changing the guideline as well since the default in the code is using reservoir sampling:)

https://github.com/yilundu/improved_contrastive_divergence#training-cifar-10-models

**Comment by yilundu** [comment]
Oh thanks for pointing that out! I didn't notice it earlier, just fixed it

**Comment by yilundu** [comment]
Could you elaborate a bit more? The default code for training on CIFAR-10 does not have the --reservoir added as a command line argument (which would enable the reservoir buffer). I'm probably missing something though

**Comment by GloryyrolG** [comment]
~Oh, my bad. I did not realize the tensorflow `flag` is different from `argparse`. Thanks.~

**Comment by GloryyrolG** [comment]
@yilundu , the args show,

```
Values of args:  {'alias': False, 'all_step': False, 'alsologtostderr': False, 'anneal': False, 'batch_size': 128, 'buffer_size': 10000, 'cond': False, 'cond_idx': 0, 'cuda': True, 'data_workers': 4, 'dataset': 'cifar10', 'ensembles': 1, 'epoch_num': 10000, 'exp': 'cifar10_model', 'filter_dim': 64, 'gpus': 1, 'hmc': False, 'im_size': 32, 'kl': True, 'kl_coeff': 1.0, 'log_dir': '', 'log_grad': False, 'log_interval': 10, 'logdir': 'cachedir', 'logger_levels': {}, 'logtostderr': False, 'lr': 0.0002, 'master_addr': '8.8.8.8', 'multiscale': True, 'node_rank': 0, 'nodes': 1, 'noise_scale': 1.0, 'norm': True, 'num_steps': 40, 'objective': 'cd', 'only_check_args': False, 'op_conversion_fallback_to_while_loop': False, 'pdb': False, 'pdb_post_mortem': False, 'port': '10002', 'profile_file': None, 'repel_im': True, 'replay_batch': True, 'reservoir': True, 'resume_iter': 0, 'run_with_pdb': False, 'run_with_profiling': False, 'save_interval': 1000, 'self_attn': True, 'showprefixforinfo': True, 'sigmoid': False, 'slurm': False, 'spec_norm': False, 'square_energy': False, 'stderrthreshold': 'fatal', 'step_lr': 100.0, 'test_interval': 1000, 'test_random_seed': 301, 'test_randomize_ordering_seed': '', 'test_srcdir': '', 'test_tmpdir': '/tmp/absl_testing', 'train': True, 'transform': True, 'use_cprofile_for_profiling': True, 'v': -1, 'verbosity': -1, 'xml_output_file': ''}
```

**Comment by yilundu** [comment]
Ahh sorry, thanks for catching this! Yes I'll update the code soon so that reservoir is not turned on by default.
